In [4]:
# You should only need to run this cell once when you (re)start the kernel. Thereafter, includet should import any changes.
using Pkg
Pkg.activate("../..") # change this to your package-install location

using MLDatasets: MNIST
using ImageCore
using Flux: onehotbatch, onecold

using Revise
includet("activations_and_losses.jl")
includet("dense_network_model.jl")
includet("dense_network_training.jl")

  Activating project at `~/Workspace/CSC381`


In [5]:
train_x, train_y = MNIST.traindata()
test_x,  test_y  = MNIST.testdata()

train_set_size = size(train_x)[end]
test_set_size = size(test_x)[end]
image_dimensions = size(train_x)[1:end-1]

println(train_set_size, " points in the training set")
println(test_set_size, " points in the training set")
println("image inputs have dimension ", image_dimensions)

60000 points in the training set
10000 points in the training set
image inputs have dimension (28, 28)


In [15]:
image_ID = rand(1:train_set_size)
println("image #", image_ID, ", label = ", train_y[image_ID])
MNIST.convert2image(train_x[:,:,image_ID])

image #54542, label = 2


In [3]:
num_inputs = image_dimensions[1] * image_dimensions[2]
num_labels = length(unique(train_y))
hidden_sizes = [15]
hidden_activations = [ReLU_activation]
output_activation = softmax_activation
nn1 = DenseNetworkCPU(num_inputs, num_labels, hidden_sizes; hidden_activations=hidden_activations, output_activation=output_activation);
nn2 = DenseNetworkGPU(num_inputs, num_labels, hidden_sizes; hidden_activations=hidden_activations, output_activation=output_activation);

In [ ]:
#TODO: set up inputs & targets

In [ ]:
#TODO: train the networks

In [7]:
a = ones(3,5)
a[2,2] = 3
a

3×5 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0
 1.0  3.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [8]:
sum(a, dims=1)

1×5 Matrix{Float64}:
 3.0  5.0  3.0  3.0  3.0

In [9]:
a ./ sum(a, dims=1)

3×5 Matrix{Float64}:
 0.333333  0.2  0.333333  0.333333  0.333333
 0.333333  0.6  0.333333  0.333333  0.333333
 0.333333  0.2  0.333333  0.333333  0.333333

In [19]:
outs = rand(3, 3)

3×3 Matrix{Float64}:
 0.408381   0.861235   0.179791
 0.0814513  0.668763   0.835128
 0.789869   0.0271192  0.815878

In [20]:
targ = ones(3, 3)

3×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [26]:
(outs .- targ)

3×3 Matrix{Float64}:
 -0.591619  -0.138765  -0.820209
 -0.918549  -0.331237  -0.164872
 -0.210131  -0.972881  -0.184122